using UnityEngine;
using System.Collections;

// 背景音乐
public enum MusicEnum
{
	NONE,
	BGM_HOME_01,			// 主界面
	BGM_GAMEPLAY_02,
	BGM_GAMEPLAY_WIN_03,
	BGM_GAMEPLAY_LOSE_04
}

// 音效
public enum SoundEnum
{
	NONE = 0,

	UI_DEFAULT_CLICK_01 = 1,	// 默认按钮声音

	UI_BUTTON_LEVEL_UP_02 = 2,	// 升级按钮
	UI_BUTTON_SELL_03 = 3,		// 出售按钮

	UI_BUILDING_MENU_SHOW_04 = 4,		// 建筑菜单出现
	UI_BUILDING_MENU_INVALID_05 = 5,	// 建筑菜单不可用 （比如点到障碍，或者敌方建筑）
	UI_BUILDING_MENU_SUBITEM_06 = 6,	// 选中建筑菜单子项

	UI_BUTTON_LEVEL_SELECT_07 = 7,		// 选中关卡

	GAMEPLAY_ALLY_BUILDING_CONSTRUCT_DONE_08 = 8,
	GAMEPLAY_ALLY_BUILDING_DESTROY_09 = 9,

	GAMEPLAY_ENEMY_BUILDING_DESTROY_10 = 10,

	GAMEPLAY_ENEMY_BOSS1_DIE_11 = 11,
	GAMEPLAY_ENEMY_BOSS2_DIE_12 = 12,

	GAMEPLAY_ENEMY_UNIT1_DIE_13 = 13,
	GAMEPLAY_ENEMY_UNIT2_DIE_14 = 14,
	GAMEPLAY_ENEMY_UNIT3_DIE_15 = 15,
	GAMEPLAY_ENEMY_UNIT4_DIE_16 = 16,
	GAMEPLAY_ENEMY_UNIT5_DIE_17 = 17,

	GAMEPLAY_BULLET_FIRE_18 = 18,
	GAMEPLAY_LASER_FIRE_19 = 19,
	GAMEPLAY_BOMB_FIRE_20 = 20,
	GAMEPLAY_BOMB_LAND_21 = 21,

	COUNTDOWN_321_22 = 22,
	COUNTDOWN_GO_23 = 23
}

